server:
  port: 8090


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://120.25.63.219:3306/intelligentInvestment?characterEncoding=utf-8&useSSL=false
  application:
    name: DNUI-Core

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
